NumericSequenceCalculator/NumericSequenceCalculator/Models/Calculate.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NumericSequenceCalculator.Models
{
    public class Calculate
    {
        [RegularExpression("^([1-9][0-9]*)$", ErrorMessage = "Enter only positive non zero whole number")]
        [Required(ErrorMessage = "Please enter a number.")]
        public int NumberToGenerate { get; set; }

        public string SequenceName { get; set; }


    }
}

NumericSequenceCalculator/NumericSequenceCalculator/Models/ViewModels/SequenceResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NumericSequenceCalculator.Models.ViewModels
{
    public class SequenceResult
    {
        public string Number { get; set; }

        public IList<string> GetEvenNumbers(int NumberToGenerate)
        {
            var numberList = Enumerable.Range(1, NumberToGenerate).ToList().Where(i => i % 2 == 0);
            return numberList.ToList().ConvertAll<string>(x => x.ToString());
        }
        public IList<string> GetOddNumbers(int NumberToGenerate)
        {
            var numberList = Enumerable.Range(1, NumberToGenerate).ToList().Where(i => i % 2 != 0);
            return numberList.ToList().ConvertAll<string>(x => x.ToString());
        }
        public IList<string> GetFibonacciNumbers(int NumberToGenerate)
        {
            int ord1 = 0, ord2 = 0, ord3 = 0;
            var FibSeries = Enumerable.Range(1, NumberToGenerate).Select(a =>
               {
                   ord1 = a == 1 ? 0 : ord2;
                   ord2 = a == 1 ? 1 : ord3;
                   ord3 = a == 1 ? 0 : ord1 + ord2;
                   return ord3;
               });
            return FibSeries.ToList().ConvertAll<string>(x => x.ToString());
        }
        public IList<string> GetMultiples(int NumberToGenerate)
        {
            var list = Enumerable.Range(1, NumberToGenerate).ToList().Select(i => i.ToString()).ToArray();
            for (int i = 0; i < list.Length; i++)
            {
                if (Convert.ToInt32(list[i]) % 3 == 0 && Convert.ToInt32(list[i]) % 5 == 0)
                    list[i] = "Z";
                else
                if (Convert.ToInt32(list[i]) % 3 == 0)
                    list[i] = "C";
                else
                if (Convert.ToInt32(list[i]) % 5 == 0)
                    list[i] = "E";
               
            }
            return list.ToList<string>();
        }
    }
}

NumericSequenceCalculator/NumericSequenceCalculator/Controllers/CalculateController.cs
using NumericSequenceCalculator.Models;
using NumericSequenceCalculator.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NumericSequenceCalculator.Controllers
{
    public class CalculateController : Controller
    {
        // GET: Calculate
     
        public ActionResult GetSequence()
        {

             return View("GetSequence");
        }
                
        public ActionResult _SequenceNumbers(int Number,string SequenceName)
        {
            var model = new List<SequenceResult>();
            if (this.ModelState.IsValid)
            {
                switch (SequenceName)
                {
                    case "All":
                        model = Enumerable.Range(1, Number).ToList().ConvertAll<string>(x => x.ToString()).Select(x => new SequenceResult { Number = x }).ToList();
                        break;
                    case "Even":
                        model = new SequenceResult().GetEvenNumbers(Number).Select(x => new SequenceResult { Number = x }).ToList();
                        break;
                    case "Odd":
                        model = new SequenceResult().GetOddNumbers(Number).Select(x => new SequenceResult { Number = x }).ToList();
                        break;
                    case "Fibonacci":
                        model = new SequenceResult().GetFibonacciNumbers(Number).Select(x => new SequenceResult { Number = x }).ToList();
                        break;
                    case "Multiples":
                        model = new SequenceResult().GetMultiples(Number).Select(x => new SequenceResult { Number = x }).ToList();
                        break;
                    default:
                        break;
                }

                return PartialView("_SequenceNumbers", model);
            }
            else return View();
        }
    }
}

NumericSequenceCalculator/NumericSequenceCalculator/Controllers/InstructionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NumericSequenceCalculator.Controllers
{
    public class InstructionsController : Controller
    {
        public ActionResult ReadMe()
        {
            return View("ReadMe");
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact Details";

            return View("Contact");
        }
    }
}

NumericSequenceCalculator/NumericSequenceCalculator/Views/Calculate/GetSequence.cshtml
@model NumericSequenceCalculator.Models.Calculate

@{
    ViewBag.Title = "GetSequence";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@*<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"> </script>*@
@section Scripts
{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#loadNumbers").on("click", function () {

            if($("form").valid()) {
                var Url = "@Url.Action("_SequenceNumbers", "Calculate")";
                var number = document.getElementById('NumberToGenerate').value;
                var sequence = $('[name="SequenceName"]:checked').val();;

                $.get("/Calculate/_SequenceNumbers/", "number=" + number + "&SequenceName=" + sequence, function (data) {
                    $("#partialViewContainer").html(data);
                });
            }

        });

        var settngs = $.data($('form')[0], 'validator').settings;
        settngs.onfocusout = function (element) { $(element).valid(); };
    });
</script>
<br /><br />
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset id="form1">
        <div class="editor-field">
            <br /><label>Enter Number to generate sequence : </label>
            @Html.TextBoxFor(model => model.NumberToGenerate, new { autofocus = true })
            @Html.ValidationMessageFor(model => model.NumberToGenerate)
        </div>
        <div class="editor-field">
            <br />
            @Html.RadioButtonFor(model => model.SequenceName, "All", new { id = "rbAll", Checked = "checked" })
            @Html.Label("rbAllNumbers", "All numbers")
            @Html.RadioButtonFor(model => model.SequenceName, "Even", new { id = "rbEven" })
            @Html.Label("rbEven", "Even numbers")
            @Html.RadioButtonFor(model => model.SequenceName, "Odd", new { id = "rbOdd" })
            @Html.Label("rbOdd", "Odd numbers")
            @Html.RadioButtonFor(model => model.SequenceName, "Fibonacci", new { id = "rbFibonacci" })
            @Html.Label("rbOdd", "Fibonacci numbers")
            @Html.RadioButtonFor(model => model.SequenceName, "Multiples", new { id = "rbMultiples" })
            @Html.Label("rbOdd", "Multiples")
        </div>
    </fieldset>
}

<br /><input type="submit" id="loadNumbers" value="GetSequence" />
<br /><div id="partialViewContainer"></div>

NumericSequenceCalculator/NumericSequenceCalculator/Views/Calculate/_SequenceNumbers.cshtml
@model IEnumerable<NumericSequenceCalculator.Models.ViewModels.SequenceResult>


<br /><br /><label>Numbers in sequence: </label>

@foreach (var item in Model)
{
    <span>
        @Html.DisplayFor(modelItem => item.Number)</span>
    }

NumericSequenceCalculator/NumericSequenceCalculator/Views/Instructions/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Message</h2>
<br /><br /><h4>Pragyan Acharya</h4>

<address>
    <strong>Email:</strong>   <a href="mailto:patipragyan@gmail.com">patipragyan@gmail.com</a><br />
</address>

NumericSequenceCalculator/NumericSequenceCalculator/Views/Instructions/ReadMe.cshtml
@{
    ViewBag.Title = "Instructions";
}

<p>
    <h3>
        Welcome to Numeric Sequence Calculator !!!
    </h3>
    <br>
<p>
    Please read the below instruction before generating the numeric sequence.
    <br><br>
    This calculator accepts a numeric value and generates the sequence.The following numeric sequences are generated:
    <ul>
        <li>
            All numbers up to and including the number entered
        </li>
        <li>
            All odd numbers up to and including the number entered
        </li>
        <li>
            All even numbers up to and including the number entered
        </li>
        <li>
            All numbers up to and including the number entered, except when
            <ul>
                <li>
                    A number is a multiple of 3 output C, and when,
                </li>
                <li>
                    A number is a multiple of 5 output E, and when
                </li>
                <li>
                    A number is a multiple of both 3 and 5 output Z
                </li>
            </ul>
        <li>  All fibonacci number up to and including the number entered.</li>


    </ul>
</p>

NumericSequenceCalculator/NumericSequenceCalculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Numeric Sequence Calculator</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Numeric Sequence Calculator", "Readme", "Instructions", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Instructions", "Readme", "Instructions")</li>
                    <li>@Html.ActionLink("Calculate", "GetSequence", "Calculate")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Instructions")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*<footer>
            <p>&copy; @DateTime.Now.Year - Numeric Sequence Calculator</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>